version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/web_platform # Default working directory, where your project will be cloned
    steps:
    - checkout
    - run:
        name: Build Docker Container
        command: docker-compose build
    - run:
        name: Run Docker Container
        command: docker-compose up -d
    - run:
        name: Go into Docker Container
        command: docker-compose exec vue_app sh
    - run:
        name: Install Requirements
        command: npm install
    - run:
        name: Build
        command: npm run dev
